### ISSUE TITLE
json.Decoder memory leak?

### ISSUE THREAD

**Issue by tigerinus** [jcrist/msgspec#114] opened 2022-06-02 21:23 UTC
Hello,

I've got a service written in Python that reads data from ElasticSearch frequently 24/7. 

Recently I've migrated it from `orjson` to `msgspec.json`. Since then, the service runs out of memory pretty quickly.

Following https://docs.python.org/3/library/tracemalloc.html#pretty-top I'm able to capture the top 10 lines that contributes large memory usage, which turns out it's the `decode(...)` method from `msgspec.json.Decoder`

```text
Top 10 lines
#1: /app/elasticsearch_repository.py:69: 26821.3 KiB
    self.__decoder.decode(
#2: /app/prepare_data_service.py:280: 3649.2 KiB
    cache_info_rt = decoder.decode(cache_info_data)
#3: /usr/local/lib/python3.10/multiprocessing/reduction.py:51: 1568.1 KiB
    cls(buf, protocol).dump(obj)
#4: /usr/local/lib/python3.10/linecache.py:137: 628.2 KiB
    lines = fp.readlines()
#5: /usr/local/lib/python3.10/json/decoder.py:353: 82.7 KiB
    obj, end = self.scan_once(s, idx)
#6: /usr/local/lib/python3.10/multiprocessing/queues.py:122: 40.2 KiB
    return _ForkingPickler.loads(res)
#7: /usr/local/lib/python3.10/tracemalloc.py:67: 11.9 KiB
    return (self.size, self.count, self.traceback)
#8: /app/elasticsearch_repository.py:68: 3.7 KiB
    return [
#9: /usr/local/lib/python3.10/http/client.py:1293: 3.6 KiB
    self.putrequest(method, url, **skips)
#10: /app/venv/lib/python3.10/site-packages/elasticsearch/client/utils.py:347: 1.8 KiB
    return func(*args, params=params, headers=headers, **kwargs)
193 other: 70.2 KiB
Total allocated size: 32880.9 KiB
```

Here are the structs for decoding:

```python
'''
structs for msgspec
'''
from typing import Dict, List, Optional

from msgspec import Struct


class Query(Struct):
    """
    Struct for Query
    """
    date: str
    depAirport: str
    arrAirport: str


class Request(Struct):
    """
    Struct for Request
    """
    supplier: str
    tripType: str
    fareClass: str
    adultAmount: int
    childAmount: int
    infantAmount: int
    queries: List[Query]
    timestamp: int


class Segment(Struct):
    """
    Struct for Segment
    """
    fareClass: str
    depDate: str
    depTime: str
    flightNo: str
    carrier: str
    orgAirport: str
    arriveDate: str
    arriveTime: str
    dstAirport: str


class Flight(Struct):
    """
    Struct for Flight
    """
    segments: List[Segment]


class Price(Struct):
    """
    Struct for Price
    """
    price: float
    tax: float
    totalPrice: float
    seatsStatus: Optional[str] = None
    currencyCode: Optional[str] = None


class Trip(Struct):
    """
    Struct for Trip
    """
    flights: List[Flight]
    prices: Dict[str, Price]
    extended = Dict[str, str]


class Result(Struct):
    """
    Struct of Result
    """
    trips: List[Trip]


class CacheInfo(Struct):
    """
    Struct of CacheInfo
    """
    request: Request
    result: Result
```

I read from https://jcristharif.com/msgspec/structs.html#struct-nogc that

> structs referencing only scalar values (ints, strings, bools, …) won’t contribute to GC load, but structs referencing containers (lists, dicts, structs, …) will.

Is this related? What's the recommendation to resolve this issue?

Thanks!

**Comment by jcrist** [comment] 2022-06-03 01:34
Hmmm, that is alarming. If the only change is switching from `orjson` to `msgspec`, then it's possible you've found a bug somewhere. I'm very interested in tracking down what's going on here, thanks for raising this issue.

>  I'm able to capture the top 10 lines that contributes large memory usage, which turns out it's the decode(...) method from msgspec.json.Decoder

If I understand correctly, tracemalloc only reports the total allocations made at each location, not the amount currently residing in memory from those locations (so a function that naturally allocates lots of data like `Decoder.decode` will always show high, even if that memory is released). I may be wrong though.

There are a couple things that could be going wrong here:

- `msgspec` allocated objects aren't being fully released somewhere. This would likely manifest as a refcounting error somewhere in the C code, where we forget to decref a resource. I recently fixed a few memory leaks that showed up when parsing *invalid* messages, but there are no known refcounting issues when parsing valid messages.
- Somewhere your code is holding on to data longer than necessary. This coupled with msgspec generally providing less GC pressure (meaning python's GC runs less frequently) may mean you see higher than normal memory usage.

My *guess* based on your explanation is that you're running into the former in a way that I haven't hit anywhere in production yet. But I'd be happy to find it's the latter. Testing for that may be as easy as adding the following lines somewhere when starting up your application:

```python
import gc
gc.set_threshold(200)  # the default is 700, we only want GC to run more frequently, arbitrarily picking 200
```

This will likely tank performance a bit, since GC will run more frequently, but if memory usage no longer climbs then this is just a GC issue. I doubt it is though.

---
 

A few questions:

> Since then, the service runs out of memory pretty quickly.

1. How quickly is quickly? What is the memory limit that's being surpassed, and how does that compare to the peak memory when running with `orjson`? Does `msgspec` memory usage continue to grow linearly as the program runs, or does it level off somewhere just with higher memory usage?

2. Most applications decode messages, do something with the result, then fully deallocate the decoded message (think a web request handler). Does that match your application's usage? Or do you store parts of the decoded messages anywhere in memory?

3. Are you able to reproduce the memory leak parsing your messages in a loop without the rest of your application? Something like the following:

   ```python
   import itertools
   decoder = msgspec.json.Decoder(...)

   # Cycle through a list of example message buffers forever
   for msg in itertools.cycle(some_list_of_example_messages):
       decoder.decode(msg)  # decode and immediately drop the result
   ```
   If we're dealing with a reference counting bug, I'd expect the above to lead to linearly increasing memory usage over time.

4. If the above doesn't turn anything up, then is there any example code you can provide that reproduces the memory leak? It'd be easier (for me) to be able to reproduce this bug locally if possible. Otherwise, we'll need to collect more information to better pinpoint what kind of memory is leaking, and where it's coming from. You *might* find https://bloomberg.github.io/memray/live.html useful for this, but there are certainly other tools.

**Comment by tigerinus** [comment] 2022-06-03 01:56
@jcrist - Thanks for the detailed information.

Setting up for the troubleshooting steps you recommended might take a bit of time. Let me first try `gc.set_threshold(200)` and see if it's a low-hanging fruit to grab.

Will get back to you soon with update.

**Comment by tigerinus** [comment] 2022-06-03 02:37
With `memray` tool (which is awesome, thanks!), I am able to find the real contributor to the huge memory usage is `rdkafka` - the underlying lib for `confluent-python-kafka`:

![image](https://user-images.githubusercontent.com/7172560/171775494-28374ac9-d772-413d-a4e1-447235a90537.png)

The logic in the service is simply deserialize data from elasticsearch and push the data to Kafka.

Could it be possible that `memspec` is so fast, that it gives no time for C based rdkafka to release memory?

**Comment by tigerinus** [comment] 2022-06-03 23:46
FYI - I tried to repro this issue with https://github.com/tigerinus/kafka_with_orjson_vs_msgspec_in_python

But I end up finding another issue - a potential memory leak in Pickler when using with msgspec.Struct. See demo of the issue at https://github.com/tigerinus/pickle_memory_leak_with_msgspec

**Comment by jcrist** [comment] 2022-06-04 14:27
> But I end up finding another issue - a potential memory leak in Pickler when using with msgspec.Struct. See demo of the issue at https://github.com/tigerinus/pickle_memory_leak_with_msgspec

Thanks for the excellent reproducible example, this indeed was a refcounting error in `Struct.__reduce__`. I've fixed this in #117, and verified the example in your repo no longer leaks. Based on your first comment above (where I also see multiprocessing is used), I'm hoping this was the source of your original issue, but it'd be good to have you verify.

Can you install the main branch using

```console
$ pip install git+https://github.com/jcrist/msgspec.git
```

and see if your main memory issue has been resolved.

**Comment by tigerinus** [comment] 2022-06-05 00:08
@jcrist I'm happy to let you know the original issue does not repro anymore.

I did a 30min long run of the micro-service, The memory usage is a beautiful GC zigzag shape now:

![image](https://user-images.githubusercontent.com/7172560/172029558-3df9634f-9392-4f56-b37a-25dd08de659a.png)

The rdkafka thread takes only 9.1KB

Thanks for fixing. Please release the new version so I can officially update all my deployments.

**Comment by jcrist** [comment] 2022-06-07 14:03
Excellent, closing. I hope to get a release out in the next week or two.

**Closed by jcrist** 2022-06-07 14:03 UTC

**Comment by tigerinus** [comment] 2022-06-15 20:36
@jcrist - any plan of a new release with this fix?

**Comment by jcrist** [comment] 2022-06-16 17:56
As mentioned above, we should have a release out before the 21st.

**Comment by jcrist** [comment] 2022-06-20 19:02
`msgspec` 0.7.0 has been released. Wheels are available on pypi now, should be up on conda-forge once the conda-forge bots detect the change.
