### ISSUE TITLE
Add support for field converters

### ISSUE THREAD

**Issue by aedify-swi** [jcrist/msgspec#491] opened 2023-07-25 07:57 UTC
### Description

Hej there,

superb library, I really enjoy using it. I've been looking through the issues but didn't find anything on this. I don't know if this works well with your implementation, but the one thing I am missing from attrs is field converters https://www.attrs.org/en/stable/init.html#converters 

My explicit use-case would be parsing APIs where the returned data is not exactly up to (my) standards. Sometimes datetimes are encoded as unix-timestamps in miliseconds, so msgspec's automatic parsing does not work. If I could get the raw value, pass it to my own converter function `datetime.fromtimestamp(int(x)/1000)` a lot of similar use cases would be solved.

I could use post_init but this does not work with frozen models.

Currently, I am writing a second attrs class, define a converter for the filed, create the attrs class and use msgspec convert. Something like this:

```python
@attrs.define
class InputClass:
    start: datetime = attrs.field(converter=lambda x: datetime.fromtimestamp(int(x)/1000))
    end: datetime = attrs.field(converter=lambda x: datetime.fromtimestamp(int(x)/1000))

class ActualClass(msgspec.Struct, frozen=True):
    start: datetime
    end: datetime
    
input_json = {...}
input_class = InputClass(**input_json)
actual_class = msgspec.convert(input_class, ActualClass, from_attributes=True)
```
It's okay, but only maintaining a single class would be neat. 

Cheers!

EDIT: Actually, modifying repr for fields would also be a nice thing you can do in attrs and I frequently use. If you were up to adding that aswell, I'd gladly open a new issue

**Comment by jcrist** [comment] 2023-07-26 04:43
Thanks for the kind words! I believe the main use case here is a duplicate of #483.

> Sometimes datetimes are encoded as unix-timestamps in miliseconds, so msgspec's automatic parsing does not work. 

With `strict=False` we now support parsing unix timestamps (in seconds) to datetimes. If this is your only use case, I could be convinced to adopt pydantic's pragmatic approach of assuming big integers in datetime fields are in milliseconds not seconds. It feels a bit sloppy, but software is meant to be useful and that would be an easy feature to add.

---

The best way to handle your problem today is to define a subclass of the types you want to customize, use those in the annotations, and use the existing `dec_hook`/`enc_hook` mechanisms to override how serialization works. This has a bunch of caveats (namely custom types like this don't work with unions), but if it works for you this would be more efficient and simpler than your current approach. Something like:

```python
import datetime

import msgspec


class unixms(datetime.datetime):
    pass


def enc_hook(x):
    if isinstance(x, unixms):
        return x.timestamp() * 1000
    raise NotImplementedError


def dec_hook(typ, x):
    if typ is unixms:
        return unixms.fromtimestamp(x / 1000, datetime.timezone.utc)
    raise NotImplementedError


class LoginEvent(msgspec.Struct):
    name: str
    timestamp: unixms


msg = b'{"name": "alice", "timestamp": 1690346418357.0}'


event = msgspec.json.decode(msg, type=LoginEvent, dec_hook=dec_hook)
print(event)
#> LoginEvent(
#>   name='alice',
#>   timestamp=unixms(2023, 7, 26, 4, 40, 18, 357000, tzinfo=datetime.timezone.utc)
#> )

msg2 = msgspec.json.encode(event, enc_hook=enc_hook)
print(msg2)
#> b'{"name":"alice","timestamp":1690346418357.0}'
```

**Comment by jcrist** [comment] 2023-07-26 04:49
> EDIT: Actually, modifying repr for fields would also be a nice thing you can do in attrs and I frequently use. If you were up to adding that aswell, I'd gladly open a new issue

I'm curious how you envision that working. If you wouldn't mind opening an issue, I'd be happy to discuss there. No promises it'll be implemented, but there's no harm in asking.

---

Also, not sure if you're aware, but `msgspec` supports encoding/decoding attrs types natively: https://jcristharif.com/msgspec/supported-types.html#attrs.

For new code there's not a strong reason to use attrs with msgspec (Struct types are much more performant and have extra features), but for existing code bases the hope is this allows for a smoother transition to using msgspec. Since you're an attrs user, I'd value some feedback on our attrs integration - there may be some rough edges/missing features here that make using attrs with msgspec less useful than it could be.

**Comment by jcrist** [comment] 2023-07-26 15:02
Thanks for the replies. Can you respond to this bit? If this is your only current blocker it'd be a quick thing to fix:

>  If this is your only use case, I could be convinced to adopt pydantic's pragmatic approach of assuming big integers in datetime fields are in milliseconds not seconds. It feels a bit sloppy, but software is meant to be useful and that would be an easy feature to add.

---

> Well now that I read again, would you want to have both validation and conversion in one function? It surely works, but to me it would feel better so separate them. I do like the way [attrs.field handles this](https://www.attrs.org/en/stable/examples.html#conversion).

I suspect we'd want a few hooks (probably one for before the builtin conversion/validation bits run and one for after). If you have feedback on the design please comment on that issue.

>  I'll check this, but I think using msgspec.convert does not trigger the attrs field converters (maybe using the attributes flag).

To clarify a bit, `msgspec.convert` and the `decode` functions all provide the same conversion/validation paths. The simplest demo of the behavior you're talking about would be:

```python
In [1]: import msgspec, attrs

In [2]: @attrs.define
   ...: class Example:
   ...:     x: int
   ...:     y: int = attrs.field(converter=int)
   ...: 

In [3]: msg = b'{"x": 1, "y": 2}'  # a valid message

In [4]: msgspec.json.decode(msg, type=Example)
Out[4]: Example(x=1, y=2)

In [5]: msg2 = b'{"x": 1, "y": "2"}'  # an invalid message

In [6]: msgspec.json.decode(msg2, type=Example)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[6], line 1
----> 1 msgspec.json.decode(msg2, type=Example)

ValidationError: Expected `int`, got `str` - at `$.y`
```

We currently don't do anything with attrs converters. My reasoning was that IMO converters are for handling flexibility on the python side (so users can call `Example(1, "2")` and have things "just work"). But when decoding they felt like the wrong place to handle this logic. You might want your python code to be able to construct an attrs object from a wider set of types than you'd want to support in a REST api - coupling the types supported in `__init__` to the types supported in `decode` felt wrong. That said, I'm not an attrs user so I'm not 100% sure what's expected behavior here.

**Closed** 2023-07-26 16:02 UTC
