### ISSUE TITLE
Issues with enum serialization

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#209] opened 2022-11-23 20:32 UTC
Hiya,

This library looks very promising. We are working on integrating it with [Starlite](https://github.com/starlite-api/starlite). One issue we came up with the lack of support for serializing `Enum` values  into JSON. So we would like to report this issue.

**Comment by provinzkraut** [comment] 2022-11-23 20:42
Chiming in here real quick:

The issue isn't that  `Enum`s aren't supported (they are). The issue for us is that they are serialized differently than we currently serialize them with `orjson`, i.e. they are being serialized into their respective **names** and not their values. 

Since there is currently no way to override how natively supported types are serialized (`enc_hook` only allows to *extend* serialization to support non-natively supported types), this would mean a breaking change for us, which unfortunately means it's going to be very hard to adopt `msgspec`. 

Are there any known workarounds for this / ways we can solve our issue?

**Comment by jcrist** [comment] 2022-11-24 15:10
Thanks for opening this.

> We are working on integrating it with Starlite.

Nice! Please let me know if you run into any other issues or have questions, use cases like Starlite are one of the main reasons I wrote msgspec.

> they are being serialized into their respective names and not their values.

This was an early decision based on a specific use case I had at the time, but it seems like most other tools encode/decode by value instead. I've been thinking about changing this to match (still only string or int values for now). This issue is enough of a motivation to make that change, shouldn't be that much work.

> Are there any known workarounds for this / ways we can solve our issue?

There are not any workarounds for this unfortunately. This can only be fixed by changing the behavior in msgspec.

Can you continue integration work without this fix? I'll hopefully have time in the next few weeks to fix this and get a new release out.

**Comment by provinzkraut** [comment] 2022-11-24 15:25
Thanks for getting back so quickly!

> I've been thinking about changing this to match

Lovely!

> Can you continue integration work without this fix? I'll hopefully have time in the next few weeks to fix this and get a new release out.

It's not a pressing matter really. If we integrate it it will probably go into the `2.0` release.

**Closed** 2022-11-28 04:07 UTC

**Comment by provinzkraut** [comment] 2022-11-30 15:25
@jcrist Thanks for the work on this again! If you don't mind me asking, is there any ETA when this changes makes it into a release?

**Comment by provinzkraut** [comment] 2022-12-06 16:31
Can confirm that it works! I have a working branch with the Starlite integration using `msgspec@main`for about a week now! Added that as soon as you merged the `Enum` update.
Sorry for not mentioning it sooner.
